let suggestions = [
    'Attack on Titan',
    'Attack on Titan Final Season Part 3',
    "Attack on Titan Final Season Part 2",
    "Ao Ashi",
    "Attack on Titan Final Season Part 1",
    "Attack on Titan Season 3 Part 2",
    "Akebi s Sailor Uniform",
    "Attack on Titan Season 2",
    "Attack on Titan Season 3 Part 1",
    "Bleach TYBW Season 2",
    "Black Clover Sword of the Wizard King",
    'Blue Lock',
    'Black Clover',
    'Bleach',
    'Boruto Naruto next Generation',
    'Berserk',
    "Bleach Thousand Year Blood War Arc",,
    "Black Rock Shooter Dawn Fall",
    "Berserk Season 2",
    "Bleach The Sealed Sword Frenzy",
    "Bleach the Movie : Hell Verse",
    "Bleach the Movie : Fade to Black",
    "Bleach the Movie : Memories of Nobody",
    "Bleach the Movie : The DiamondDust Rebellion",
    'Chainsaw Man',
    'Cowboy Bebop',
    "Demon Slayer Swordsmith Village Arc",
    'Dr Stone New World',
    'Dragon Ball Super',,
    "Darling in The FranXX",
    'Dragon Ball Z',
    'Demon Slayer (Kimetsu no Yaiba)',
    'Death Note',
    "Demon Slayer Entertainment District Arc",
    "Demon Slayer Mugen Train Arc",
    "Demon Slayer Siblings Bond",
    "Demon Slayer Hashira Meeting Arc",
    "Demon Slayer Mt.Natagumo Arc",
    "Dragon Ball Super : Super Hero",
    "Dragon Ball",
    "Dr Stone",
    "Dragon Ball GT",
    "Dragon Ball Super Movie Broly",
    "Dr Stone: Stone Wars",
    "Dr Stone: Ryuusui",
    "Dr Stone: Stone Wars Eve of the Battle Special Feature",
    "Dragon Ball Z Kai",,
    "Fire Force Season 2",
    "Fire Force",
    'Full Metal Alchemist : Brotherhood',
    "Hell's Paradise",
    'Hunter X Hunter',
    'Jujutsu Kaisen Season 2',
    'Jujutsu Kaisen',
    "Jujutsu Kaisen 0 Movie",
    'Mashle',
    'My Hero Academia',
    'My Star',
    "My Hero Academia Season 6",
    "My Hero Academia Season 2",,
    "My Dress Up Darling",
    "Miss Kuroitsu from the Monster Development Department",
    "My Hero Academia Season 3",
    "My Hero Academia Season 4",
    "My Hero Academia Season 5",
    "My Hero Academia Heroes Rising",
    'Naruto',
    "Naruto Shippuden",
    "Naruto Shippuden Movie Road to Ninja",
    "Naruto Shippuden Movie 4 The Lost Toour",
    "Naruto Movie The Last",
    "Naruto Movie 1: Ninja Clash in the Land of Snow",
    'One Piece',
    "One Piece Film Red",
    'One Punch Man',
    "One Punch Man Season 2",
    "One Piece Film Gold",
    "One Piece Movie 1",
    "One Punch Man Specials",
    "One Piece Episode Skypiea",
    "One Piece Film Stampede",
    "One Piece 3D Stravat chase",
    "One Punch Man Season 2 Specials",
    "Ranking of Kings",
    "Radiant",
    "Radiant Season 2",
    'Steins;Gate',
    "Summer Time",
    'Tokyo Revengers',
    "Tokyo Revengers Christmas Showdown",
    "The Ancient Magus Bride",
    "The Ancient Magus Bride Season 2",
    "Tokyo 24th Ward",
    "Toilet Bound Hanako Kun",
    'Vinland Saga',
    "Vinland Saga Season 2",
    "Zom 100"
]
